### ISSUE TITLE
VPN Icon on HTC10

### ISSUE THREAD

**Issue by blueJack92** [zacharee/SystemUITunerRedesign#10]
There is an issue with the VPN icon on my HTC10. I can not hide the icon. Other icons work fine.

**Comment by osk2** [comment]
I can confirm this issue, toggle VPN icon off won't actually hide the icon.

I'm using HTC 10 with stock Android 7.0

**Comment by blueJack92** [comment]
Any updates?

**Comment by zacharee** [comment]
It's not something I can fix.


On Nov 26, 2017 at 6:41 PM, <blueJack92 <notifications@github.com>> wrote:

Any updates?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/SystemUITunerRedesign/issues/10#issuecomment-347048701>,
or mute the thread
