### ISSUE TITLE
Power Notifications

### ISSUE THREAD

**Issue by jzimmer14** [zacharee/SystemUITunerRedesign#13]
I have enabled Power Notifications on my Samsung Galaxy S7 Edge, with Nougat 7.0.  I go into my settings, and it appears as though Power Notifications have been activated because the slide scale bar is visible.  however,  I still can not make any changes to this.  Is this something in Samsung that they will not allow users to manage power notifications?

**Comment by zacharee** [comment]
There's some complicated method to making them work on TouchWiz, which I
unfortunately don't know.


On Nov 26, 2017 at 5:04 PM, <jzimmer14 <notifications@github.com>> wrote:

I have enabled Power Notifications on my Samsung Galaxy S7 Edge, with
Nougat 7.0. I go into my settings, and it appears as though Power
Notifications have been activated because the slide scale bar is visible.
however, I still can not make any changes to this. Is this something in
Samsung that they will not allow users to manage power notifications?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/SystemUITunerRedesign/issues/13>, or mute the
thread
