### ISSUE TITLE
No Changes

### ISSUE THREAD

**Issue by TweenJRStudio** [zacharee/SystemUITunerRedesign#21]
The Problem is not the App , but when I use it to change my UI nothing happens and after reboot the Buttons are in the correct possition, but nothing happens
I've got a Huawei p8 lite 2017

**Comment by zacharee** [comment]
What buttons?

Sent from Astro <https://www.helloastro.com> for Android

On 5/19/18 at 6:42 AM, TweenJRStudio wrote:

The Problem is not the App , but when I use it to change my UI nothing
happens and after reboot the Buttons are in the correct possition, but
nothing happens
I've got a Huawei p8 lite 2017

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/SystemUITunerRedesign/issues/21>, or mute the
thread

**Comment by TweenJRStudio** [comment]
![screenshot_20180519-135545](https://user-images.githubusercontent.com/30803473/40268379-76ac5990-5b6c-11e8-980c-2f1fbed08b0e.png)
Didn't knew how to name them those sliders

**Comment by zacharee** [comment]
I still don't know what you're talking about.

Sent from Astro <https://www.helloastro.com> for Android

On 5/19/18 at 7:57 AM, TweenJRStudio wrote:

[image: screenshot_20180519-135545]
<https://user-images.githubusercontent.com/30803473/40268379-76ac5990-5b6c-11e8-980c-2f1fbed08b0e.png>
Didn't knew how to name them those sliders

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/SystemUITunerRedesign/issues/21#issuecomment-390400118>,
or mute the thread

**Comment by TweenJRStudio** [comment]
Ok i simplify it The app does nothing for me

**Comment by zacharee** [comment]
I'm not sure what you want me to do then.

Sent from Astro <https://www.helloastro.com> for Android

On 5/19/18 at 8:01 AM, TweenJRStudio wrote:

Ok i simplify it The app does nothing for me

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/SystemUITunerRedesign/issues/21#issuecomment-390400321>,
or mute the thread

**Comment by TweenJRStudio** [comment]
Does this App only support Touch Wizz

**Comment by zacharee** [comment]
No.

Sent from Astro <https://www.helloastro.com> for Android

On 5/19/18 at 8:10 AM, TweenJRStudio wrote:

Does this App only support Touch Wizz

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/SystemUITunerRedesign/issues/21#issuecomment-390400796>,
or mute the thread

**Comment by TweenJRStudio** [comment]
But then I dont understand why it is not working for me, I was using the App half a year ago and it was working fine now I wanted to try it again and everything I can edit with this app does nothing
E.g.
When I toggle Immersivemods nothing happens

**Comment by TweenJRStudio** [comment]
Is now working
